tgthrProgramManagement/force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit Log</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tgthrProgramManagement/force-app/main/default/objects/Audit_Log__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Action performed (Read, Update, etc...)</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tgthrProgramManagement/force-app/main/default/objects/Audit_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Details about the event</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

tgthrProgramManagement/force-app/main/default/objects/Audit_Log__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <description>Type of object being logged</description>
    <label>Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tgthrProgramManagement/force-app/main/default/objects/Audit_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The Salesforce record Id that was accessed.</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

tgthrProgramManagement/force-app/main/default/objects/Audit_Log__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>Exact time of event</description>
    <label>Timestamp</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

tgthrProgramManagement/force-app/main/default/objects/Audit_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who initiated or triggered event</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

tgthrProgramManagement/force-app/main/default/objects/Audit_Log__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>52</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

tgthrProgramManagement/force-app/main/default/objects/InteractionSummary/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>52</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

tgthrProgramManagement/force-app/main/default/classes/AuditLogService.cls
public with sharing class AuditLogService {

    @AuraEnabled
    public static void logAction(String actionType, String entityId, String details, String objectType) {
        SObject auditLogSObj = (SObject) Type.forName('Audit_Log__c').newInstance();
        auditLogSObj.put('Action__c', actionType);
        auditLogSObj.put('UUID__c', entityId);
        auditLogSObj.put('Description__c', details);
        auditLogSObj.put('Object_Type__c', objectType);
        auditLogSObj.put('User__c', UserInfo.getUserId());
        auditLogSObj.put('Timestamp__c', System.now());
        insert auditLogSObj;
    }

    @AuraEnabled
    public static List<SObject> getAuditLogsByEntity(String entityId, Integer maxRows) {
        Integer m = (maxRows == null || maxRows <= 0 || maxRows > 2000) ? 50 : maxRows;
        String query = 'SELECT Id, Action__c, Description__c, Object_Type__c, User__c, Timestamp__c FROM Audit_Log__c WHERE Record_Id__c = :entityId ORDER BY Timestamp__c DESC LIMIT :m';
        return Database.query(query);
    }

    @AuraEnabled
    public static void logForPersonAccount(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'PersonAccount');
    }

    @AuraEnabled
    public static void logForInteractionSummary(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'InteractionSummary');
    }

    @AuraEnabled
    public static void logForCase(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'Case');
    }

    @AuraEnabled
    public static void logForGoalAssignment(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'GoalAssignment');
    }

    @AuraEnabled
    public static void logForDiagnoses(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'Diagnoses');
    }

    @AuraEnabled
    public static void logForInterview(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'Interview');
    }

    @AuraEnabled
    public static void logForAssessment(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'Assessment');
    }

    @AuraEnabled
    public static void logForCarePlan(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'CarePlan');
    }

    @AuraEnabled
    public static void logForReferral(String actionType, String entityId, String details) {
        logAction(actionType, entityId, details, 'Referral');
    }
}